CREATE TABLE public.TB_PRODUTO (
	COD_PRODUTO CHAR(4) primary KEY,
	DES_PRODUTO VARCHAR(30) NULL,
	STA_STATUS CHAR(4) NULL
);

CREATE TABLE public.TB_PRODUTO_COSIF (
	COD_COSIF CHAR(11) PRIMARY KEY,
	COD_PRODUTO CHAR(4) NOT NULL,
	COD_CLASSIFICACAO CHAR(6) NULL,
	STA_STATUS CHAR(1) NULL,
	CONSTRAINT COD_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES TB_PRODUTO(COD_PRODUTO)
);

CREATE TABLE public.TB_MOVIMENTO_MANUAL(
	DAT_MES NUMERIC(2) NOT NULL,
	DAT_ANO NUMERIC(4) NOT NULL,
	NUM_LANCAMENTO NUMERIC(18) NOT NULL,
	COD_PRODUTO CHAR(4) NOT NULL,
	COD_COSIF CHAR(11) NOT NULL,
	DES_DESCRICAO CHAR(11),
	DAT_MOVIMENTO TIMESTAMP,
	COD_USUARIO VARCHAR(15),
	VAL_VALOR NUMERIC(18,2),
	PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO),
	CONSTRAINT COD_COSIF FOREIGN KEY(COD_COSIF) REFERENCES TB_PRODUTO_COSIF(COD_COSIF),
	CONSTRAINT COD_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES TB_PRODUTO(COD_PRODUTO)
);

